import { expect, test } from 'vitest'
import { getWasmMemory } from '../utils'
import type { entry } from './conway.actual'

const e0 =
`$$.......
.........
.........
....$....
...$$$...
....$....
.........
.........`;

const e1 =
`.........
.........
.........
...$$$...
...$.$...
...$$$...
.........
.........`;

const e2 =
`.........
.........
....$....
...$.$...
..$...$..
...$.$...
....$....
.........`;

const e3 =
`.........
.........
....$....
...$$$...
..$$.$$..
...$$$...
....$....
.........`;

const name = 'conway';
test(name, async () => {
  const entry = getWasmMemory("from-c", name);
  expect(await entry(0)).toStrictEqual(e0);
  expect(await entry(1)).toStrictEqual(e1);
  expect(await entry(2)).toStrictEqual(e2);
  expect(await entry(3)).toStrictEqual(e3);
});

// type x = entry<[0]>;
//   ^?

type testCases = [
  // Expect<Equal<entry<[0]>, typeof e0>>,
  // Expect<Equal<entry<[1]>, typeof e1>>,
  // Expect<Equal<entry<[2]>, typeof e2>>,
  // Expect<Equal<entry<[3]>, typeof e3>>,
]