import type { Func, runProgram } from 'wasm-to-typescript-types'
import type { StoreString } from 'ts-type-math'

type $__wasm_call_ctors<
  RESULT extends Func = {
    kind: 'func';
    params: [];
    result: number;
    locals: [];
    instructions: [
      { kind: 'Call'; id: '$emscripten_stack_init' },
    ];
  }
> = RESULT

type $countAliveNeighbors<
  RESULT extends Func = {
    kind: 'func';
    params: ['$p0', '$p1', '$p2', '$p3', '$p4', '$p5'];
    result: number;
    locals: ['$l6', '$l7', '$l8', '$l9', '$l10', '$l11', '$l12', '$l13', '$l14', '$l15', '$l16', '$l17', '$l18', '$l19', '$l20', '$l21', '$l22', '$l23', '$l24', '$l25', '$l26', '$l27', '$l28', '$l29', '$l30', '$l31', '$l32', '$l33', '$l34', '$l35', '$l36', '$l37', '$l38', '$l39', '$l40', '$l41', '$l42', '$l43', '$l44', '$l45', '$l46', '$l47', '$l48', '$l49', '$l50', '$l51', '$l52', '$l53', '$l54', '$l55', '$l56', '$l57', '$l58', '$l59', '$l60', '$l61', '$l62', '$l63', '$l64', '$l65', '$l66', '$l67', '$l68', '$l69', '$l70', '$l71', '$l72', '$l73', '$l74', '$l75', '$l76', '$l77', '$l78', '$l79', '$l80', '$l81', '$l82', '$l83'];
    instructions: [
      { kind: 'GlobalGet'; id: '$__stack_pointer' },
      { kind: 'LocalSet'; id: '$l6' },
      { kind: 'Const'; value: 48 },
      { kind: 'LocalSet'; id: '$l7' },
      { kind: 'LocalGet'; id: '$l6' },
      { kind: 'LocalGet'; id: '$l7' },
      { kind: 'Subtract' },
      { kind: 'LocalSet'; id: '$l8' },
      { kind: 'LocalGet'; id: '$l8' },
      { kind: 'LocalGet'; id: '$p0' },
      { kind: 'I32Store'; offset: 44 },
      { kind: 'LocalGet'; id: '$l8' },
      { kind: 'LocalGet'; id: '$p1' },
      { kind: 'I32Store'; offset: 40 },
      { kind: 'LocalGet'; id: '$l8' },
      { kind: 'LocalGet'; id: '$p2' },
      { kind: 'I32Store'; offset: 36 },
      { kind: 'LocalGet'; id: '$l8' },
      { kind: 'LocalGet'; id: '$p3' },
      { kind: 'I32Store'; offset: 32 },
      { kind: 'LocalGet'; id: '$l8' },
      { kind: 'LocalGet'; id: '$p4' },
      { kind: 'I32Store'; offset: 28 },
      { kind: 'LocalGet'; id: '$l8' },
      { kind: 'LocalGet'; id: '$p5' },
      { kind: 'I32Store'; offset: 24 },
      { kind: 'LocalGet'; id: '$l8' },
      { kind: 'I32Load'; offset: 24 },
      { kind: 'LocalSet'; id: '$l9' },
      { kind: 'Const'; value: 0 },
      { kind: 'LocalSet'; id: '$l10' },
      { kind: 'LocalGet'; id: '$l9' },
      { kind: 'LocalGet'; id: '$l10' },
      { kind: 'I32Store'; offset: 0 },
      { kind: 'Const'; value: -1 },
      { kind: 'LocalSet'; id: '$l11' },
      { kind: 'LocalGet'; id: '$l8' },
      { kind: 'LocalGet'; id: '$l11' },
      { kind: 'I32Store'; offset: 20 },
      { kind: 'Block';
        id: '$B0';
        instructions: [
          { kind: 'Loop';
            id: '$L1';
            instructions: [
              { kind: 'LocalGet'; id: '$l8' },
              { kind: 'I32Load'; offset: 20 },
              { kind: 'LocalSet'; id: '$l12' },
              { kind: 'Const'; value: 1 },
              { kind: 'LocalSet'; id: '$l13' },
              { kind: 'LocalGet'; id: '$l12' },
              { kind: 'LocalSet'; id: '$l14' },
              { kind: 'LocalGet'; id: '$l13' },
              { kind: 'LocalSet'; id: '$l15' },
              { kind: 'LocalGet'; id: '$l14' },
              { kind: 'LocalGet'; id: '$l15' },
              { kind: 'LessThanOrEqual' },
              { kind: 'LocalSet'; id: '$l16' },
              { kind: 'Const'; value: 1 },
              { kind: 'LocalSet'; id: '$l17' },
              { kind: 'LocalGet'; id: '$l16' },
              { kind: 'LocalGet'; id: '$l17' },
              { kind: 'And' },
              { kind: 'LocalSet'; id: '$l18' },
              { kind: 'LocalGet'; id: '$l18' },
              { kind: 'EqualsZero' },
              { kind: 'BranchIf'; id: '$B0' },
              { kind: 'Const'; value: -1 },
              { kind: 'LocalSet'; id: '$l19' },
              { kind: 'LocalGet'; id: '$l8' },
              { kind: 'LocalGet'; id: '$l19' },
              { kind: 'I32Store'; offset: 16 },
              { kind: 'Block';
                id: '$B2';
                instructions: [
                  { kind: 'Loop';
                    id: '$L3';
                    instructions: [
                      { kind: 'LocalGet'; id: '$l8' },
                      { kind: 'I32Load'; offset: 16 },
                      { kind: 'LocalSet'; id: '$l20' },
                      { kind: 'Const'; value: 1 },
                      { kind: 'LocalSet'; id: '$l21' },
                      { kind: 'LocalGet'; id: '$l20' },
                      { kind: 'LocalSet'; id: '$l22' },
                      { kind: 'LocalGet'; id: '$l21' },
                      { kind: 'LocalSet'; id: '$l23' },
                      { kind: 'LocalGet'; id: '$l22' },
                      { kind: 'LocalGet'; id: '$l23' },
                      { kind: 'LessThanOrEqual' },
                      { kind: 'LocalSet'; id: '$l24' },
                      { kind: 'Const'; value: 1 },
                      { kind: 'LocalSet'; id: '$l25' },
                      { kind: 'LocalGet'; id: '$l24' },
                      { kind: 'LocalGet'; id: '$l25' },
                      { kind: 'And' },
                      { kind: 'LocalSet'; id: '$l26' },
                      { kind: 'LocalGet'; id: '$l26' },
                      { kind: 'EqualsZero' },
                      { kind: 'BranchIf'; id: '$B2' },
                      { kind: 'LocalGet'; id: '$l8' },
                      { kind: 'I32Load'; offset: 20 },
                      { kind: 'LocalSet'; id: '$l27' },
                      { kind: 'Block';
                        id: '$B4';
                        instructions: [
                          { kind: 'Block';
                            id: '$B5';
                            instructions: [
                              { kind: 'LocalGet'; id: '$l27' },
                              { kind: 'BranchIf'; id: '$B5' },
                              { kind: 'LocalGet'; id: '$l8' },
                              { kind: 'I32Load'; offset: 16 },
                              { kind: 'LocalSet'; id: '$l28' },
                              { kind: 'LocalGet'; id: '$l28' },
                              { kind: 'BranchIf'; id: '$B5' },
                              { kind: 'Branch'; id: '$B4' },
                            ];
                          },
                          { kind: 'LocalGet'; id: '$l8' },
                          { kind: 'I32Load'; offset: 32 },
                          { kind: 'LocalSet'; id: '$l29' },
                          { kind: 'LocalGet'; id: '$l8' },
                          { kind: 'I32Load'; offset: 20 },
                          { kind: 'LocalSet'; id: '$l30' },
                          { kind: 'LocalGet'; id: '$l29' },
                          { kind: 'LocalGet'; id: '$l30' },
                          { kind: 'Add' },
                          { kind: 'LocalSet'; id: '$l31' },
                          { kind: 'LocalGet'; id: '$l8' },
                          { kind: 'LocalGet'; id: '$l31' },
                          { kind: 'I32Store'; offset: 12 },
                          { kind: 'LocalGet'; id: '$l8' },
                          { kind: 'I32Load'; offset: 28 },
                          { kind: 'LocalSet'; id: '$l32' },
                          { kind: 'LocalGet'; id: '$l8' },
                          { kind: 'I32Load'; offset: 16 },
                          { kind: 'LocalSet'; id: '$l33' },
                          { kind: 'LocalGet'; id: '$l32' },
                          { kind: 'LocalGet'; id: '$l33' },
                          { kind: 'Add' },
                          { kind: 'LocalSet'; id: '$l34' },
                          { kind: 'LocalGet'; id: '$l8' },
                          { kind: 'LocalGet'; id: '$l34' },
                          { kind: 'I32Store'; offset: 8 },
                          { kind: 'LocalGet'; id: '$l8' },
                          { kind: 'I32Load'; offset: 12 },
                          { kind: 'LocalSet'; id: '$l35' },
                          { kind: 'Const'; value: 0 },
                          { kind: 'LocalSet'; id: '$l36' },
                          { kind: 'LocalGet'; id: '$l35' },
                          { kind: 'LocalSet'; id: '$l37' },
                          { kind: 'LocalGet'; id: '$l36' },
                          { kind: 'LocalSet'; id: '$l38' },
                          { kind: 'LocalGet'; id: '$l37' },
                          { kind: 'LocalGet'; id: '$l38' },
                          { kind: 'GreaterThanOrEqual' },
                          { kind: 'LocalSet'; id: '$l39' },
                          { kind: 'Const'; value: 1 },
                          { kind: 'LocalSet'; id: '$l40' },
                          { kind: 'LocalGet'; id: '$l39' },
                          { kind: 'LocalGet'; id: '$l40' },
                          { kind: 'And' },
                          { kind: 'LocalSet'; id: '$l41' },
                          { kind: 'Block';
                            id: '$B6';
                            instructions: [
                              { kind: 'LocalGet'; id: '$l41' },
                              { kind: 'EqualsZero' },
                              { kind: 'BranchIf'; id: '$B6' },
                              { kind: 'LocalGet'; id: '$l8' },
                              { kind: 'I32Load'; offset: 12 },
                              { kind: 'LocalSet'; id: '$l42' },
                              { kind: 'LocalGet'; id: '$l8' },
                              { kind: 'I32Load'; offset: 40 },
                              { kind: 'LocalSet'; id: '$l43' },
                              { kind: 'LocalGet'; id: '$l42' },
                              { kind: 'LocalSet'; id: '$l44' },
                              { kind: 'LocalGet'; id: '$l43' },
                              { kind: 'LocalSet'; id: '$l45' },
                              { kind: 'LocalGet'; id: '$l44' },
                              { kind: 'LocalGet'; id: '$l45' },
                              { kind: 'LessThan' },
                              { kind: 'LocalSet'; id: '$l46' },
                              { kind: 'Const'; value: 1 },
                              { kind: 'LocalSet'; id: '$l47' },
                              { kind: 'LocalGet'; id: '$l46' },
                              { kind: 'LocalGet'; id: '$l47' },
                              { kind: 'And' },
                              { kind: 'LocalSet'; id: '$l48' },
                              { kind: 'LocalGet'; id: '$l48' },
                              { kind: 'EqualsZero' },
                              { kind: 'BranchIf'; id: '$B6' },
                              { kind: 'LocalGet'; id: '$l8' },
                              { kind: 'I32Load'; offset: 8 },
                              { kind: 'LocalSet'; id: '$l49' },
                              { kind: 'Const'; value: 0 },
                              { kind: 'LocalSet'; id: '$l50' },
                              { kind: 'LocalGet'; id: '$l49' },
                              { kind: 'LocalSet'; id: '$l51' },
                              { kind: 'LocalGet'; id: '$l50' },
                              { kind: 'LocalSet'; id: '$l52' },
                              { kind: 'LocalGet'; id: '$l51' },
                              { kind: 'LocalGet'; id: '$l52' },
                              { kind: 'GreaterThanOrEqual' },
                              { kind: 'LocalSet'; id: '$l53' },
                              { kind: 'Const'; value: 1 },
                              { kind: 'LocalSet'; id: '$l54' },
                              { kind: 'LocalGet'; id: '$l53' },
                              { kind: 'LocalGet'; id: '$l54' },
                              { kind: 'And' },
                              { kind: 'LocalSet'; id: '$l55' },
                              { kind: 'LocalGet'; id: '$l55' },
                              { kind: 'EqualsZero' },
                              { kind: 'BranchIf'; id: '$B6' },
                              { kind: 'LocalGet'; id: '$l8' },
                              { kind: 'I32Load'; offset: 8 },
                              { kind: 'LocalSet'; id: '$l56' },
                              { kind: 'LocalGet'; id: '$l8' },
                              { kind: 'I32Load'; offset: 36 },
                              { kind: 'LocalSet'; id: '$l57' },
                              { kind: 'LocalGet'; id: '$l56' },
                              { kind: 'LocalSet'; id: '$l58' },
                              { kind: 'LocalGet'; id: '$l57' },
                              { kind: 'LocalSet'; id: '$l59' },
                              { kind: 'LocalGet'; id: '$l58' },
                              { kind: 'LocalGet'; id: '$l59' },
                              { kind: 'LessThan' },
                              { kind: 'LocalSet'; id: '$l60' },
                              { kind: 'Const'; value: 1 },
                              { kind: 'LocalSet'; id: '$l61' },
                              { kind: 'LocalGet'; id: '$l60' },
                              { kind: 'LocalGet'; id: '$l61' },
                              { kind: 'And' },
                              { kind: 'LocalSet'; id: '$l62' },
                              { kind: 'LocalGet'; id: '$l62' },
                              { kind: 'EqualsZero' },
                              { kind: 'BranchIf'; id: '$B6' },
                              { kind: 'LocalGet'; id: '$l8' },
                              { kind: 'I32Load'; offset: 44 },
                              { kind: 'LocalSet'; id: '$l63' },
                              { kind: 'LocalGet'; id: '$l8' },
                              { kind: 'I32Load'; offset: 12 },
                              { kind: 'LocalSet'; id: '$l64' },
                              { kind: 'Const'; value: 9 },
                              { kind: 'LocalSet'; id: '$l65' },
                              { kind: 'LocalGet'; id: '$l64' },
                              { kind: 'LocalGet'; id: '$l65' },
                              { kind: 'Multiply' },
                              { kind: 'LocalSet'; id: '$l66' },
                              { kind: 'LocalGet'; id: '$l63' },
                              { kind: 'LocalGet'; id: '$l66' },
                              { kind: 'Add' },
                              { kind: 'LocalSet'; id: '$l67' },
                              { kind: 'LocalGet'; id: '$l8' },
                              { kind: 'I32Load'; offset: 8 },
                              { kind: 'LocalSet'; id: '$l68' },
                              { kind: 'LocalGet'; id: '$l67' },
                              { kind: 'LocalGet'; id: '$l68' },
                              { kind: 'Add' },
                              { kind: 'LocalSet'; id: '$l69' },
                              { kind: 'LocalGet'; id: '$l69' },
                              { kind: 'I32Load8u'; offset: 0 },
                              { kind: 'LocalSet'; id: '$l70' },
                              { kind: 'Const'; value: 24 },
                              { kind: 'LocalSet'; id: '$l71' },
                              { kind: 'LocalGet'; id: '$l70' },
                              { kind: 'LocalGet'; id: '$l71' },
                              { kind: 'ShiftLeft' },
                              { kind: 'LocalSet'; id: '$l72' },
                              { kind: 'LocalGet'; id: '$l72' },
                              { kind: 'LocalGet'; id: '$l71' },
                              { kind: 'ShiftRight' },
                              { kind: 'LocalSet'; id: '$l73' },
                              { kind: 'LocalGet'; id: '$l73' },
                              { kind: 'EqualsZero' },
                              { kind: 'BranchIf'; id: '$B6' },
                              { kind: 'LocalGet'; id: '$l8' },
                              { kind: 'I32Load'; offset: 24 },
                              { kind: 'LocalSet'; id: '$l74' },
                              { kind: 'LocalGet'; id: '$l74' },
                              { kind: 'I32Load'; offset: 0 },
                              { kind: 'LocalSet'; id: '$l75' },
                              { kind: 'Const'; value: 1 },
                              { kind: 'LocalSet'; id: '$l76' },
                              { kind: 'LocalGet'; id: '$l75' },
                              { kind: 'LocalGet'; id: '$l76' },
                              { kind: 'Add' },
                              { kind: 'LocalSet'; id: '$l77' },
                              { kind: 'LocalGet'; id: '$l74' },
                              { kind: 'LocalGet'; id: '$l77' },
                              { kind: 'I32Store'; offset: 0 },
                            ];
                          },
                        ];
                      },
                      { kind: 'LocalGet'; id: '$l8' },
                      { kind: 'I32Load'; offset: 16 },
                      { kind: 'LocalSet'; id: '$l78' },
                      { kind: 'Const'; value: 1 },
                      { kind: 'LocalSet'; id: '$l79' },
                      { kind: 'LocalGet'; id: '$l78' },
                      { kind: 'LocalGet'; id: '$l79' },
                      { kind: 'Add' },
                      { kind: 'LocalSet'; id: '$l80' },
                      { kind: 'LocalGet'; id: '$l8' },
                      { kind: 'LocalGet'; id: '$l80' },
                      { kind: 'I32Store'; offset: 16 },
                      { kind: 'Branch'; id: '$L3' },
                    ];
                  },
                  { kind: 'Unreachable' },
                ];
              },
              { kind: 'LocalGet'; id: '$l8' },
              { kind: 'I32Load'; offset: 20 },
              { kind: 'LocalSet'; id: '$l81' },
              { kind: 'Const'; value: 1 },
              { kind: 'LocalSet'; id: '$l82' },
              { kind: 'LocalGet'; id: '$l81' },
              { kind: 'LocalGet'; id: '$l82' },
              { kind: 'Add' },
              { kind: 'LocalSet'; id: '$l83' },
              { kind: 'LocalGet'; id: '$l8' },
              { kind: 'LocalGet'; id: '$l83' },
              { kind: 'I32Store'; offset: 20 },
              { kind: 'Branch'; id: '$L1' },
            ];
          },
          { kind: 'Unreachable' },
        ];
      },
      { kind: 'Return'; count: 0 },
    ];
  }
> = RESULT

type $updateGrid<
  RESULT extends Func = {
    kind: 'func';
    params: ['$p0', '$p1', '$p2'];
    result: number;
    locals: ['$l3', '$l4', '$l5', '$l6', '$l7', '$l8', '$l9', '$l10', '$l11', '$l12', '$l13', '$l14', '$l15', '$l16', '$l17', '$l18', '$l19', '$l20', '$l21', '$l22', '$l23', '$l24', '$l25', '$l26', '$l27', '$l28', '$l29', '$l30', '$l31', '$l32', '$l33', '$l34', '$l35', '$l36', '$l37', '$l38', '$l39', '$l40', '$l41', '$l42', '$l43', '$l44', '$l45', '$l46', '$l47', '$l48', '$l49', '$l50', '$l51', '$l52', '$l53', '$l54', '$l55', '$l56', '$l57', '$l58', '$l59', '$l60', '$l61', '$l62', '$l63', '$l64', '$l65', '$l66', '$l67', '$l68', '$l69', '$l70', '$l71', '$l72', '$l73', '$l74', '$l75', '$l76', '$l77', '$l78', '$l79', '$l80', '$l81', '$l82', '$l83', '$l84', '$l85', '$l86', '$l87', '$l88', '$l89', '$l90', '$l91', '$l92', '$l93', '$l94', '$l95', '$l96', '$l97', '$l98', '$l99', '$l100', '$l101', '$l102', '$l103', '$l104', '$l105', '$l106', '$l107', '$l108', '$l109', '$l110', '$l111', '$l112', '$l113', '$l114', '$l115', '$l116', '$l117', '$l118', '$l119', '$l120', '$l121', '$l122'];
    instructions: [
      { kind: 'GlobalGet'; id: '$__stack_pointer' },
      { kind: 'LocalSet'; id: '$l3' },
      { kind: 'Const'; value: 128 },
      { kind: 'LocalSet'; id: '$l4' },
      { kind: 'LocalGet'; id: '$l3' },
      { kind: 'LocalGet'; id: '$l4' },
      { kind: 'Subtract' },
      { kind: 'LocalSet'; id: '$l5' },
      { kind: 'LocalGet'; id: '$l5' },
      { kind: 'GlobalSet'; id: '$__stack_pointer' },
      { kind: 'LocalGet'; id: '$l5' },
      { kind: 'LocalGet'; id: '$p0' },
      { kind: 'I32Store'; offset: 124 },
      { kind: 'LocalGet'; id: '$l5' },
      { kind: 'LocalGet'; id: '$p1' },
      { kind: 'I32Store'; offset: 120 },
      { kind: 'LocalGet'; id: '$l5' },
      { kind: 'LocalGet'; id: '$p2' },
      { kind: 'I32Store'; offset: 116 },
      { kind: 'Const'; value: 0 },
      { kind: 'LocalSet'; id: '$l6' },
      { kind: 'LocalGet'; id: '$l5' },
      { kind: 'LocalGet'; id: '$l6' },
      { kind: 'I32Store'; offset: 28 },
      { kind: 'Block';
        id: '$B0';
        instructions: [
          { kind: 'Loop';
            id: '$L1';
            instructions: [
              { kind: 'LocalGet'; id: '$l5' },
              { kind: 'I32Load'; offset: 28 },
              { kind: 'LocalSet'; id: '$l7' },
              { kind: 'LocalGet'; id: '$l5' },
              { kind: 'I32Load'; offset: 120 },
              { kind: 'LocalSet'; id: '$l8' },
              { kind: 'LocalGet'; id: '$l7' },
              { kind: 'LocalSet'; id: '$l9' },
              { kind: 'LocalGet'; id: '$l8' },
              { kind: 'LocalSet'; id: '$l10' },
              { kind: 'LocalGet'; id: '$l9' },
              { kind: 'LocalGet'; id: '$l10' },
              { kind: 'LessThan' },
              { kind: 'LocalSet'; id: '$l11' },
              { kind: 'Const'; value: 1 },
              { kind: 'LocalSet'; id: '$l12' },
              { kind: 'LocalGet'; id: '$l11' },
              { kind: 'LocalGet'; id: '$l12' },
              { kind: 'And' },
              { kind: 'LocalSet'; id: '$l13' },
              { kind: 'LocalGet'; id: '$l13' },
              { kind: 'EqualsZero' },
              { kind: 'BranchIf'; id: '$B0' },
              { kind: 'Const'; value: 0 },
              { kind: 'LocalSet'; id: '$l14' },
              { kind: 'LocalGet'; id: '$l5' },
              { kind: 'LocalGet'; id: '$l14' },
              { kind: 'I32Store'; offset: 24 },
              { kind: 'Block';
                id: '$B2';
                instructions: [
                  { kind: 'Loop';
                    id: '$L3';
                    instructions: [
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 24 },
                      { kind: 'LocalSet'; id: '$l15' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 116 },
                      { kind: 'LocalSet'; id: '$l16' },
                      { kind: 'LocalGet'; id: '$l15' },
                      { kind: 'LocalSet'; id: '$l17' },
                      { kind: 'LocalGet'; id: '$l16' },
                      { kind: 'LocalSet'; id: '$l18' },
                      { kind: 'LocalGet'; id: '$l17' },
                      { kind: 'LocalGet'; id: '$l18' },
                      { kind: 'LessThan' },
                      { kind: 'LocalSet'; id: '$l19' },
                      { kind: 'Const'; value: 1 },
                      { kind: 'LocalSet'; id: '$l20' },
                      { kind: 'LocalGet'; id: '$l19' },
                      { kind: 'LocalGet'; id: '$l20' },
                      { kind: 'And' },
                      { kind: 'LocalSet'; id: '$l21' },
                      { kind: 'LocalGet'; id: '$l21' },
                      { kind: 'EqualsZero' },
                      { kind: 'BranchIf'; id: '$B2' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 124 },
                      { kind: 'LocalSet'; id: '$l22' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 120 },
                      { kind: 'LocalSet'; id: '$l23' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 116 },
                      { kind: 'LocalSet'; id: '$l24' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 28 },
                      { kind: 'LocalSet'; id: '$l25' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 24 },
                      { kind: 'LocalSet'; id: '$l26' },
                      { kind: 'Const'; value: 20 },
                      { kind: 'LocalSet'; id: '$l27' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'LocalGet'; id: '$l27' },
                      { kind: 'Add' },
                      { kind: 'LocalSet'; id: '$l28' },
                      { kind: 'LocalGet'; id: '$l28' },
                      { kind: 'LocalSet'; id: '$l29' },
                      { kind: 'LocalGet'; id: '$l22' },
                      { kind: 'LocalGet'; id: '$l23' },
                      { kind: 'LocalGet'; id: '$l24' },
                      { kind: 'LocalGet'; id: '$l25' },
                      { kind: 'LocalGet'; id: '$l26' },
                      { kind: 'LocalGet'; id: '$l29' },
                      { kind: 'Call'; id: '$countAliveNeighbors' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 124 },
                      { kind: 'LocalSet'; id: '$l30' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 28 },
                      { kind: 'LocalSet'; id: '$l31' },
                      { kind: 'Const'; value: 9 },
                      { kind: 'LocalSet'; id: '$l32' },
                      { kind: 'LocalGet'; id: '$l31' },
                      { kind: 'LocalGet'; id: '$l32' },
                      { kind: 'Multiply' },
                      { kind: 'LocalSet'; id: '$l33' },
                      { kind: 'LocalGet'; id: '$l30' },
                      { kind: 'LocalGet'; id: '$l33' },
                      { kind: 'Add' },
                      { kind: 'LocalSet'; id: '$l34' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 24 },
                      { kind: 'LocalSet'; id: '$l35' },
                      { kind: 'LocalGet'; id: '$l34' },
                      { kind: 'LocalGet'; id: '$l35' },
                      { kind: 'Add' },
                      { kind: 'LocalSet'; id: '$l36' },
                      { kind: 'LocalGet'; id: '$l36' },
                      { kind: 'I32Load8u'; offset: 0 },
                      { kind: 'LocalSet'; id: '$l37' },
                      { kind: 'Const'; value: 24 },
                      { kind: 'LocalSet'; id: '$l38' },
                      { kind: 'LocalGet'; id: '$l37' },
                      { kind: 'LocalGet'; id: '$l38' },
                      { kind: 'ShiftLeft' },
                      { kind: 'LocalSet'; id: '$l39' },
                      { kind: 'LocalGet'; id: '$l39' },
                      { kind: 'LocalGet'; id: '$l38' },
                      { kind: 'ShiftRight' },
                      { kind: 'LocalSet'; id: '$l40' },
                      { kind: 'Block';
                        id: '$B4';
                        instructions: [
                          { kind: 'Block';
                            id: '$B5';
                            instructions: [
                              { kind: 'LocalGet'; id: '$l40' },
                              { kind: 'EqualsZero' },
                              { kind: 'BranchIf'; id: '$B5' },
                              { kind: 'LocalGet'; id: '$l5' },
                              { kind: 'I32Load'; offset: 20 },
                              { kind: 'LocalSet'; id: '$l41' },
                              { kind: 'Const'; value: 2 },
                              { kind: 'LocalSet'; id: '$l42' },
                              { kind: 'LocalGet'; id: '$l41' },
                              { kind: 'LocalSet'; id: '$l43' },
                              { kind: 'LocalGet'; id: '$l42' },
                              { kind: 'LocalSet'; id: '$l44' },
                              { kind: 'LocalGet'; id: '$l43' },
                              { kind: 'LocalGet'; id: '$l44' },
                              { kind: 'Equals' },
                              { kind: 'LocalSet'; id: '$l45' },
                              { kind: 'Const'; value: 1 },
                              { kind: 'LocalSet'; id: '$l46' },
                              { kind: 'Const'; value: 1 },
                              { kind: 'LocalSet'; id: '$l47' },
                              { kind: 'LocalGet'; id: '$l45' },
                              { kind: 'LocalGet'; id: '$l47' },
                              { kind: 'And' },
                              { kind: 'LocalSet'; id: '$l48' },
                              { kind: 'LocalGet'; id: '$l46' },
                              { kind: 'LocalSet'; id: '$l49' },
                              { kind: 'Block';
                                id: '$B6';
                                instructions: [
                                  { kind: 'LocalGet'; id: '$l48' },
                                  { kind: 'BranchIf'; id: '$B6' },
                                  { kind: 'LocalGet'; id: '$l5' },
                                  { kind: 'I32Load'; offset: 20 },
                                  { kind: 'LocalSet'; id: '$l50' },
                                  { kind: 'Const'; value: 3 },
                                  { kind: 'LocalSet'; id: '$l51' },
                                  { kind: 'LocalGet'; id: '$l50' },
                                  { kind: 'LocalSet'; id: '$l52' },
                                  { kind: 'LocalGet'; id: '$l51' },
                                  { kind: 'LocalSet'; id: '$l53' },
                                  { kind: 'LocalGet'; id: '$l52' },
                                  { kind: 'LocalGet'; id: '$l53' },
                                  { kind: 'Equals' },
                                  { kind: 'LocalSet'; id: '$l54' },
                                  { kind: 'LocalGet'; id: '$l54' },
                                  { kind: 'LocalSet'; id: '$l49' },
                                ];
                              },
                              { kind: 'LocalGet'; id: '$l49' },
                              { kind: 'LocalSet'; id: '$l55' },
                              { kind: 'Const'; value: 1 },
                              { kind: 'LocalSet'; id: '$l56' },
                              { kind: 'LocalGet'; id: '$l55' },
                              { kind: 'LocalGet'; id: '$l56' },
                              { kind: 'And' },
                              { kind: 'LocalSet'; id: '$l57' },
                              { kind: 'LocalGet'; id: '$l57' },
                              { kind: 'LocalSet'; id: '$l58' },
                              { kind: 'Branch'; id: '$B4' },
                            ];
                          },
                          { kind: 'LocalGet'; id: '$l5' },
                          { kind: 'I32Load'; offset: 20 },
                          { kind: 'LocalSet'; id: '$l59' },
                          { kind: 'Const'; value: 3 },
                          { kind: 'LocalSet'; id: '$l60' },
                          { kind: 'LocalGet'; id: '$l59' },
                          { kind: 'LocalSet'; id: '$l61' },
                          { kind: 'LocalGet'; id: '$l60' },
                          { kind: 'LocalSet'; id: '$l62' },
                          { kind: 'LocalGet'; id: '$l61' },
                          { kind: 'LocalGet'; id: '$l62' },
                          { kind: 'Equals' },
                          { kind: 'LocalSet'; id: '$l63' },
                          { kind: 'Const'; value: 1 },
                          { kind: 'LocalSet'; id: '$l64' },
                          { kind: 'LocalGet'; id: '$l63' },
                          { kind: 'LocalGet'; id: '$l64' },
                          { kind: 'And' },
                          { kind: 'LocalSet'; id: '$l65' },
                          { kind: 'LocalGet'; id: '$l65' },
                          { kind: 'LocalSet'; id: '$l58' },
                        ];
                      },
                      { kind: 'LocalGet'; id: '$l58' },
                      { kind: 'LocalSet'; id: '$l66' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 28 },
                      { kind: 'LocalSet'; id: '$l67' },
                      { kind: 'Const'; value: 32 },
                      { kind: 'LocalSet'; id: '$l68' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'LocalGet'; id: '$l68' },
                      { kind: 'Add' },
                      { kind: 'LocalSet'; id: '$l69' },
                      { kind: 'LocalGet'; id: '$l69' },
                      { kind: 'LocalSet'; id: '$l70' },
                      { kind: 'Const'; value: 9 },
                      { kind: 'LocalSet'; id: '$l71' },
                      { kind: 'LocalGet'; id: '$l67' },
                      { kind: 'LocalGet'; id: '$l71' },
                      { kind: 'Multiply' },
                      { kind: 'LocalSet'; id: '$l72' },
                      { kind: 'LocalGet'; id: '$l70' },
                      { kind: 'LocalGet'; id: '$l72' },
                      { kind: 'Add' },
                      { kind: 'LocalSet'; id: '$l73' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 24 },
                      { kind: 'LocalSet'; id: '$l74' },
                      { kind: 'LocalGet'; id: '$l73' },
                      { kind: 'LocalGet'; id: '$l74' },
                      { kind: 'Add' },
                      { kind: 'LocalSet'; id: '$l75' },
                      { kind: 'LocalGet'; id: '$l75' },
                      { kind: 'LocalGet'; id: '$l66' },
                      { kind: 'I32Store8'; offset: 0 },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 24 },
                      { kind: 'LocalSet'; id: '$l76' },
                      { kind: 'Const'; value: 1 },
                      { kind: 'LocalSet'; id: '$l77' },
                      { kind: 'LocalGet'; id: '$l76' },
                      { kind: 'LocalGet'; id: '$l77' },
                      { kind: 'Add' },
                      { kind: 'LocalSet'; id: '$l78' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'LocalGet'; id: '$l78' },
                      { kind: 'I32Store'; offset: 24 },
                      { kind: 'Branch'; id: '$L3' },
                    ];
                  },
                  { kind: 'Unreachable' },
                ];
              },
              { kind: 'LocalGet'; id: '$l5' },
              { kind: 'I32Load'; offset: 28 },
              { kind: 'LocalSet'; id: '$l79' },
              { kind: 'Const'; value: 1 },
              { kind: 'LocalSet'; id: '$l80' },
              { kind: 'LocalGet'; id: '$l79' },
              { kind: 'LocalGet'; id: '$l80' },
              { kind: 'Add' },
              { kind: 'LocalSet'; id: '$l81' },
              { kind: 'LocalGet'; id: '$l5' },
              { kind: 'LocalGet'; id: '$l81' },
              { kind: 'I32Store'; offset: 28 },
              { kind: 'Branch'; id: '$L1' },
            ];
          },
          { kind: 'Unreachable' },
        ];
      },
      { kind: 'Const'; value: 0 },
      { kind: 'LocalSet'; id: '$l82' },
      { kind: 'LocalGet'; id: '$l5' },
      { kind: 'LocalGet'; id: '$l82' },
      { kind: 'I32Store'; offset: 16 },
      { kind: 'Block';
        id: '$B7';
        instructions: [
          { kind: 'Loop';
            id: '$L8';
            instructions: [
              { kind: 'LocalGet'; id: '$l5' },
              { kind: 'I32Load'; offset: 16 },
              { kind: 'LocalSet'; id: '$l83' },
              { kind: 'LocalGet'; id: '$l5' },
              { kind: 'I32Load'; offset: 120 },
              { kind: 'LocalSet'; id: '$l84' },
              { kind: 'LocalGet'; id: '$l83' },
              { kind: 'LocalSet'; id: '$l85' },
              { kind: 'LocalGet'; id: '$l84' },
              { kind: 'LocalSet'; id: '$l86' },
              { kind: 'LocalGet'; id: '$l85' },
              { kind: 'LocalGet'; id: '$l86' },
              { kind: 'LessThan' },
              { kind: 'LocalSet'; id: '$l87' },
              { kind: 'Const'; value: 1 },
              { kind: 'LocalSet'; id: '$l88' },
              { kind: 'LocalGet'; id: '$l87' },
              { kind: 'LocalGet'; id: '$l88' },
              { kind: 'And' },
              { kind: 'LocalSet'; id: '$l89' },
              { kind: 'LocalGet'; id: '$l89' },
              { kind: 'EqualsZero' },
              { kind: 'BranchIf'; id: '$B7' },
              { kind: 'Const'; value: 0 },
              { kind: 'LocalSet'; id: '$l90' },
              { kind: 'LocalGet'; id: '$l5' },
              { kind: 'LocalGet'; id: '$l90' },
              { kind: 'I32Store'; offset: 12 },
              { kind: 'Block';
                id: '$B9';
                instructions: [
                  { kind: 'Loop';
                    id: '$L10';
                    instructions: [
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 12 },
                      { kind: 'LocalSet'; id: '$l91' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 116 },
                      { kind: 'LocalSet'; id: '$l92' },
                      { kind: 'LocalGet'; id: '$l91' },
                      { kind: 'LocalSet'; id: '$l93' },
                      { kind: 'LocalGet'; id: '$l92' },
                      { kind: 'LocalSet'; id: '$l94' },
                      { kind: 'LocalGet'; id: '$l93' },
                      { kind: 'LocalGet'; id: '$l94' },
                      { kind: 'LessThan' },
                      { kind: 'LocalSet'; id: '$l95' },
                      { kind: 'Const'; value: 1 },
                      { kind: 'LocalSet'; id: '$l96' },
                      { kind: 'LocalGet'; id: '$l95' },
                      { kind: 'LocalGet'; id: '$l96' },
                      { kind: 'And' },
                      { kind: 'LocalSet'; id: '$l97' },
                      { kind: 'LocalGet'; id: '$l97' },
                      { kind: 'EqualsZero' },
                      { kind: 'BranchIf'; id: '$B9' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 16 },
                      { kind: 'LocalSet'; id: '$l98' },
                      { kind: 'Const'; value: 32 },
                      { kind: 'LocalSet'; id: '$l99' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'LocalGet'; id: '$l99' },
                      { kind: 'Add' },
                      { kind: 'LocalSet'; id: '$l100' },
                      { kind: 'LocalGet'; id: '$l100' },
                      { kind: 'LocalSet'; id: '$l101' },
                      { kind: 'Const'; value: 9 },
                      { kind: 'LocalSet'; id: '$l102' },
                      { kind: 'LocalGet'; id: '$l98' },
                      { kind: 'LocalGet'; id: '$l102' },
                      { kind: 'Multiply' },
                      { kind: 'LocalSet'; id: '$l103' },
                      { kind: 'LocalGet'; id: '$l101' },
                      { kind: 'LocalGet'; id: '$l103' },
                      { kind: 'Add' },
                      { kind: 'LocalSet'; id: '$l104' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 12 },
                      { kind: 'LocalSet'; id: '$l105' },
                      { kind: 'LocalGet'; id: '$l104' },
                      { kind: 'LocalGet'; id: '$l105' },
                      { kind: 'Add' },
                      { kind: 'LocalSet'; id: '$l106' },
                      { kind: 'LocalGet'; id: '$l106' },
                      { kind: 'I32Load8u'; offset: 0 },
                      { kind: 'LocalSet'; id: '$l107' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 124 },
                      { kind: 'LocalSet'; id: '$l108' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 16 },
                      { kind: 'LocalSet'; id: '$l109' },
                      { kind: 'Const'; value: 9 },
                      { kind: 'LocalSet'; id: '$l110' },
                      { kind: 'LocalGet'; id: '$l109' },
                      { kind: 'LocalGet'; id: '$l110' },
                      { kind: 'Multiply' },
                      { kind: 'LocalSet'; id: '$l111' },
                      { kind: 'LocalGet'; id: '$l108' },
                      { kind: 'LocalGet'; id: '$l111' },
                      { kind: 'Add' },
                      { kind: 'LocalSet'; id: '$l112' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 12 },
                      { kind: 'LocalSet'; id: '$l113' },
                      { kind: 'LocalGet'; id: '$l112' },
                      { kind: 'LocalGet'; id: '$l113' },
                      { kind: 'Add' },
                      { kind: 'LocalSet'; id: '$l114' },
                      { kind: 'LocalGet'; id: '$l114' },
                      { kind: 'LocalGet'; id: '$l107' },
                      { kind: 'I32Store8'; offset: 0 },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 12 },
                      { kind: 'LocalSet'; id: '$l115' },
                      { kind: 'Const'; value: 1 },
                      { kind: 'LocalSet'; id: '$l116' },
                      { kind: 'LocalGet'; id: '$l115' },
                      { kind: 'LocalGet'; id: '$l116' },
                      { kind: 'Add' },
                      { kind: 'LocalSet'; id: '$l117' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'LocalGet'; id: '$l117' },
                      { kind: 'I32Store'; offset: 12 },
                      { kind: 'Branch'; id: '$L10' },
                    ];
                  },
                  { kind: 'Unreachable' },
                ];
              },
              { kind: 'LocalGet'; id: '$l5' },
              { kind: 'I32Load'; offset: 16 },
              { kind: 'LocalSet'; id: '$l118' },
              { kind: 'Const'; value: 1 },
              { kind: 'LocalSet'; id: '$l119' },
              { kind: 'LocalGet'; id: '$l118' },
              { kind: 'LocalGet'; id: '$l119' },
              { kind: 'Add' },
              { kind: 'LocalSet'; id: '$l120' },
              { kind: 'LocalGet'; id: '$l5' },
              { kind: 'LocalGet'; id: '$l120' },
              { kind: 'I32Store'; offset: 16 },
              { kind: 'Branch'; id: '$L8' },
            ];
          },
          { kind: 'Unreachable' },
        ];
      },
      { kind: 'Const'; value: 128 },
      { kind: 'LocalSet'; id: '$l121' },
      { kind: 'LocalGet'; id: '$l5' },
      { kind: 'LocalGet'; id: '$l121' },
      { kind: 'Add' },
      { kind: 'LocalSet'; id: '$l122' },
      { kind: 'LocalGet'; id: '$l122' },
      { kind: 'GlobalSet'; id: '$__stack_pointer' },
      { kind: 'Return'; count: 0 },
    ];
  }
> = RESULT

type $displayGrid<
  RESULT extends Func = {
    kind: 'func';
    params: ['$p0', '$p1', '$p2'];
    result: number;
    locals: ['$l3', '$l4', '$l5', '$l6', '$l7', '$l8', '$l9', '$l10', '$l11', '$l12', '$l13', '$l14', '$l15', '$l16', '$l17', '$l18', '$l19', '$l20', '$l21', '$l22', '$l23', '$l24', '$l25', '$l26', '$l27', '$l28', '$l29', '$l30', '$l31', '$l32', '$l33', '$l34', '$l35', '$l36', '$l37', '$l38', '$l39', '$l40', '$l41', '$l42', '$l43', '$l44', '$l45', '$l46', '$l47', '$l48', '$l49', '$l50', '$l51', '$l52', '$l53', '$l54', '$l55', '$l56', '$l57', '$l58', '$l59', '$l60', '$l61', '$l62', '$l63', '$l64', '$l65', '$l66'];
    instructions: [
      { kind: 'GlobalGet'; id: '$__stack_pointer' },
      { kind: 'LocalSet'; id: '$l3' },
      { kind: 'Const'; value: 32 },
      { kind: 'LocalSet'; id: '$l4' },
      { kind: 'LocalGet'; id: '$l3' },
      { kind: 'LocalGet'; id: '$l4' },
      { kind: 'Subtract' },
      { kind: 'LocalSet'; id: '$l5' },
      { kind: 'LocalGet'; id: '$l5' },
      { kind: 'LocalGet'; id: '$p0' },
      { kind: 'I32Store'; offset: 28 },
      { kind: 'LocalGet'; id: '$l5' },
      { kind: 'LocalGet'; id: '$p1' },
      { kind: 'I32Store'; offset: 24 },
      { kind: 'LocalGet'; id: '$l5' },
      { kind: 'LocalGet'; id: '$p2' },
      { kind: 'I32Store'; offset: 20 },
      { kind: 'Const'; value: 0 },
      { kind: 'LocalSet'; id: '$l6' },
      { kind: 'LocalGet'; id: '$l5' },
      { kind: 'LocalGet'; id: '$l6' },
      { kind: 'I32Store'; offset: 16 },
      { kind: 'Const'; value: 0 },
      { kind: 'LocalSet'; id: '$l7' },
      { kind: 'LocalGet'; id: '$l5' },
      { kind: 'LocalGet'; id: '$l7' },
      { kind: 'I32Store'; offset: 12 },
      { kind: 'Block';
        id: '$B0';
        instructions: [
          { kind: 'Loop';
            id: '$L1';
            instructions: [
              { kind: 'LocalGet'; id: '$l5' },
              { kind: 'I32Load'; offset: 12 },
              { kind: 'LocalSet'; id: '$l8' },
              { kind: 'LocalGet'; id: '$l5' },
              { kind: 'I32Load'; offset: 24 },
              { kind: 'LocalSet'; id: '$l9' },
              { kind: 'LocalGet'; id: '$l8' },
              { kind: 'LocalSet'; id: '$l10' },
              { kind: 'LocalGet'; id: '$l9' },
              { kind: 'LocalSet'; id: '$l11' },
              { kind: 'LocalGet'; id: '$l10' },
              { kind: 'LocalGet'; id: '$l11' },
              { kind: 'LessThan' },
              { kind: 'LocalSet'; id: '$l12' },
              { kind: 'Const'; value: 1 },
              { kind: 'LocalSet'; id: '$l13' },
              { kind: 'LocalGet'; id: '$l12' },
              { kind: 'LocalGet'; id: '$l13' },
              { kind: 'And' },
              { kind: 'LocalSet'; id: '$l14' },
              { kind: 'LocalGet'; id: '$l14' },
              { kind: 'EqualsZero' },
              { kind: 'BranchIf'; id: '$B0' },
              { kind: 'Const'; value: 0 },
              { kind: 'LocalSet'; id: '$l15' },
              { kind: 'LocalGet'; id: '$l5' },
              { kind: 'LocalGet'; id: '$l15' },
              { kind: 'I32Store'; offset: 8 },
              { kind: 'Block';
                id: '$B2';
                instructions: [
                  { kind: 'Loop';
                    id: '$L3';
                    instructions: [
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 8 },
                      { kind: 'LocalSet'; id: '$l16' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 20 },
                      { kind: 'LocalSet'; id: '$l17' },
                      { kind: 'LocalGet'; id: '$l16' },
                      { kind: 'LocalSet'; id: '$l18' },
                      { kind: 'LocalGet'; id: '$l17' },
                      { kind: 'LocalSet'; id: '$l19' },
                      { kind: 'LocalGet'; id: '$l18' },
                      { kind: 'LocalGet'; id: '$l19' },
                      { kind: 'LessThan' },
                      { kind: 'LocalSet'; id: '$l20' },
                      { kind: 'Const'; value: 1 },
                      { kind: 'LocalSet'; id: '$l21' },
                      { kind: 'LocalGet'; id: '$l20' },
                      { kind: 'LocalGet'; id: '$l21' },
                      { kind: 'And' },
                      { kind: 'LocalSet'; id: '$l22' },
                      { kind: 'LocalGet'; id: '$l22' },
                      { kind: 'EqualsZero' },
                      { kind: 'BranchIf'; id: '$B2' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 16 },
                      { kind: 'LocalSet'; id: '$l23' },
                      { kind: 'Const'; value: 79 },
                      { kind: 'LocalSet'; id: '$l24' },
                      { kind: 'LocalGet'; id: '$l23' },
                      { kind: 'LocalSet'; id: '$l25' },
                      { kind: 'LocalGet'; id: '$l24' },
                      { kind: 'LocalSet'; id: '$l26' },
                      { kind: 'LocalGet'; id: '$l25' },
                      { kind: 'LocalGet'; id: '$l26' },
                      { kind: 'LessThan' },
                      { kind: 'LocalSet'; id: '$l27' },
                      { kind: 'Const'; value: 1 },
                      { kind: 'LocalSet'; id: '$l28' },
                      { kind: 'LocalGet'; id: '$l27' },
                      { kind: 'LocalGet'; id: '$l28' },
                      { kind: 'And' },
                      { kind: 'LocalSet'; id: '$l29' },
                      { kind: 'Block';
                        id: '$B4';
                        instructions: [
                          { kind: 'LocalGet'; id: '$l29' },
                          { kind: 'EqualsZero' },
                          { kind: 'BranchIf'; id: '$B4' },
                          { kind: 'LocalGet'; id: '$l5' },
                          { kind: 'I32Load'; offset: 28 },
                          { kind: 'LocalSet'; id: '$l30' },
                          { kind: 'LocalGet'; id: '$l5' },
                          { kind: 'I32Load'; offset: 12 },
                          { kind: 'LocalSet'; id: '$l31' },
                          { kind: 'Const'; value: 9 },
                          { kind: 'LocalSet'; id: '$l32' },
                          { kind: 'LocalGet'; id: '$l31' },
                          { kind: 'LocalGet'; id: '$l32' },
                          { kind: 'Multiply' },
                          { kind: 'LocalSet'; id: '$l33' },
                          { kind: 'LocalGet'; id: '$l30' },
                          { kind: 'LocalGet'; id: '$l33' },
                          { kind: 'Add' },
                          { kind: 'LocalSet'; id: '$l34' },
                          { kind: 'LocalGet'; id: '$l5' },
                          { kind: 'I32Load'; offset: 8 },
                          { kind: 'LocalSet'; id: '$l35' },
                          { kind: 'LocalGet'; id: '$l34' },
                          { kind: 'LocalGet'; id: '$l35' },
                          { kind: 'Add' },
                          { kind: 'LocalSet'; id: '$l36' },
                          { kind: 'LocalGet'; id: '$l36' },
                          { kind: 'I32Load8u'; offset: 0 },
                          { kind: 'LocalSet'; id: '$l37' },
                          { kind: 'Const'; value: 24 },
                          { kind: 'LocalSet'; id: '$l38' },
                          { kind: 'LocalGet'; id: '$l37' },
                          { kind: 'LocalGet'; id: '$l38' },
                          { kind: 'ShiftLeft' },
                          { kind: 'LocalSet'; id: '$l39' },
                          { kind: 'LocalGet'; id: '$l39' },
                          { kind: 'LocalGet'; id: '$l38' },
                          { kind: 'ShiftRight' },
                          { kind: 'LocalSet'; id: '$l40' },
                          { kind: 'Const'; value: 36 },
                          { kind: 'LocalSet'; id: '$l41' },
                          { kind: 'Const'; value: 46 },
                          { kind: 'LocalSet'; id: '$l42' },
                          { kind: 'LocalGet'; id: '$l41' },
                          { kind: 'LocalGet'; id: '$l42' },
                          { kind: 'LocalGet'; id: '$l40' },
                          { kind: 'Select' },
                          { kind: 'LocalSet'; id: '$l43' },
                          { kind: 'LocalGet'; id: '$l5' },
                          { kind: 'I32Load'; offset: 16 },
                          { kind: 'LocalSet'; id: '$l44' },
                          { kind: 'Const'; value: 1 },
                          { kind: 'LocalSet'; id: '$l45' },
                          { kind: 'LocalGet'; id: '$l44' },
                          { kind: 'LocalGet'; id: '$l45' },
                          { kind: 'Add' },
                          { kind: 'LocalSet'; id: '$l46' },
                          { kind: 'LocalGet'; id: '$l5' },
                          { kind: 'LocalGet'; id: '$l46' },
                          { kind: 'I32Store'; offset: 16 },
                          { kind: 'LocalGet'; id: '$l44' },
                          { kind: 'LocalGet'; id: '$l43' },
                          { kind: 'I32Store8'; offset: 1120 },
                        ];
                      },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'I32Load'; offset: 8 },
                      { kind: 'LocalSet'; id: '$l47' },
                      { kind: 'Const'; value: 1 },
                      { kind: 'LocalSet'; id: '$l48' },
                      { kind: 'LocalGet'; id: '$l47' },
                      { kind: 'LocalGet'; id: '$l48' },
                      { kind: 'Add' },
                      { kind: 'LocalSet'; id: '$l49' },
                      { kind: 'LocalGet'; id: '$l5' },
                      { kind: 'LocalGet'; id: '$l49' },
                      { kind: 'I32Store'; offset: 8 },
                      { kind: 'Branch'; id: '$L3' },
                    ];
                  },
                  { kind: 'Unreachable' },
                ];
              },
              { kind: 'LocalGet'; id: '$l5' },
              { kind: 'I32Load'; offset: 16 },
              { kind: 'LocalSet'; id: '$l50' },
              { kind: 'Const'; value: 79 },
              { kind: 'LocalSet'; id: '$l51' },
              { kind: 'LocalGet'; id: '$l50' },
              { kind: 'LocalSet'; id: '$l52' },
              { kind: 'LocalGet'; id: '$l51' },
              { kind: 'LocalSet'; id: '$l53' },
              { kind: 'LocalGet'; id: '$l52' },
              { kind: 'LocalGet'; id: '$l53' },
              { kind: 'LessThan' },
              { kind: 'LocalSet'; id: '$l54' },
              { kind: 'Const'; value: 1 },
              { kind: 'LocalSet'; id: '$l55' },
              { kind: 'LocalGet'; id: '$l54' },
              { kind: 'LocalGet'; id: '$l55' },
              { kind: 'And' },
              { kind: 'LocalSet'; id: '$l56' },
              { kind: 'Block';
                id: '$B5';
                instructions: [
                  { kind: 'LocalGet'; id: '$l56' },
                  { kind: 'EqualsZero' },
                  { kind: 'BranchIf'; id: '$B5' },
                  { kind: 'LocalGet'; id: '$l5' },
                  { kind: 'I32Load'; offset: 16 },
                  { kind: 'LocalSet'; id: '$l57' },
                  { kind: 'Const'; value: 1 },
                  { kind: 'LocalSet'; id: '$l58' },
                  { kind: 'LocalGet'; id: '$l57' },
                  { kind: 'LocalGet'; id: '$l58' },
                  { kind: 'Add' },
                  { kind: 'LocalSet'; id: '$l59' },
                  { kind: 'LocalGet'; id: '$l5' },
                  { kind: 'LocalGet'; id: '$l59' },
                  { kind: 'I32Store'; offset: 16 },
                  { kind: 'Const'; value: 10 },
                  { kind: 'LocalSet'; id: '$l60' },
                  { kind: 'LocalGet'; id: '$l57' },
                  { kind: 'LocalGet'; id: '$l60' },
                  { kind: 'I32Store8'; offset: 1120 },
                ];
              },
              { kind: 'LocalGet'; id: '$l5' },
              { kind: 'I32Load'; offset: 12 },
              { kind: 'LocalSet'; id: '$l61' },
              { kind: 'Const'; value: 1 },
              { kind: 'LocalSet'; id: '$l62' },
              { kind: 'LocalGet'; id: '$l61' },
              { kind: 'LocalGet'; id: '$l62' },
              { kind: 'Add' },
              { kind: 'LocalSet'; id: '$l63' },
              { kind: 'LocalGet'; id: '$l5' },
              { kind: 'LocalGet'; id: '$l63' },
              { kind: 'I32Store'; offset: 12 },
              { kind: 'Branch'; id: '$L1' },
            ];
          },
          { kind: 'Unreachable' },
        ];
      },
      { kind: 'LocalGet'; id: '$l5' },
      { kind: 'I32Load'; offset: 16 },
      { kind: 'LocalSet'; id: '$l64' },
      { kind: 'Const'; value: 0 },
      { kind: 'LocalSet'; id: '$l65' },
      { kind: 'LocalGet'; id: '$l64' },
      { kind: 'LocalGet'; id: '$l65' },
      { kind: 'I32Store8'; offset: 1120 },
      { kind: 'Const'; value: 1120 },
      { kind: 'LocalSet'; id: '$l66' },
      { kind: 'LocalGet'; id: '$l66' },
      { kind: 'Return'; count: 1 },
    ];
  }
> = RESULT

type $entry<
  RESULT extends Func = {
    kind: 'func';
    params: ['$p0'];
    result: number;
    locals: ['$l1', '$l2', '$l3', '$l4', '$l5', '$l6', '$l7', '$l8', '$l9', '$l10', '$l11', '$l12', '$l13', '$l14', '$l15', '$l16', '$l17', '$l18', '$l19', '$l20', '$l21', '$l22', '$l23', '$l24', '$l25', '$l26', '$l27', '$l28', '$l29', '$l30', '$l31', '$l32', '$l33', '$l34', '$l35', '$l36', '$l37', '$l38', '$l39', '$l40', '$l41', '$l42', '$l43', '$l44', '$l45', '$l46', '$l47', '$l48', '$l49', '$l50', '$l51', '$l52', '$l53', '$l54', '$l55', '$l56', '$l57', '$l58', '$l59', '$l60', '$l61', '$l62', '$l63', '$l64', '$l65', '$l66', '$l67', '$l68', '$l69', '$l70', '$l71'];
    instructions: [
      { kind: 'GlobalGet'; id: '$__stack_pointer' },
      { kind: 'LocalSet'; id: '$l1' },
      { kind: 'Const'; value: 208 },
      { kind: 'LocalSet'; id: '$l2' },
      { kind: 'LocalGet'; id: '$l1' },
      { kind: 'LocalGet'; id: '$l2' },
      { kind: 'Subtract' },
      { kind: 'LocalSet'; id: '$l3' },
      { kind: 'LocalGet'; id: '$l3' },
      { kind: 'GlobalSet'; id: '$__stack_pointer' },
      { kind: 'LocalGet'; id: '$l3' },
      { kind: 'LocalGet'; id: '$p0' },
      { kind: 'I32Store'; offset: 204 },
      { kind: 'Const'; value: 16 },
      { kind: 'LocalSet'; id: '$l4' },
      { kind: 'LocalGet'; id: '$l3' },
      { kind: 'LocalGet'; id: '$l4' },
      { kind: 'Add' },
      { kind: 'LocalSet'; id: '$l5' },
      { kind: 'LocalGet'; id: '$l5' },
      { kind: 'LocalSet'; id: '$l6' },
      { kind: 'Const'; value: 1024 },
      { kind: 'LocalSet'; id: '$l7' },
      { kind: 'Const'; value: 81 },
      { kind: 'LocalSet'; id: '$l8' },
      { kind: 'LocalGet'; id: '$l6' },
      { kind: 'LocalGet'; id: '$l7' },
      { kind: 'LocalGet'; id: '$l8' },
      { kind: 'Call'; id: '$__memcpy' },
      { kind: 'Drop' },
      { kind: 'Const'; value: 0 },
      { kind: 'LocalSet'; id: '$l9' },
      { kind: 'LocalGet'; id: '$l3' },
      { kind: 'LocalGet'; id: '$l9' },
      { kind: 'I32Store'; offset: 12 },
      { kind: 'Block';
        id: '$B0';
        instructions: [
          { kind: 'Loop';
            id: '$L1';
            instructions: [
              { kind: 'LocalGet'; id: '$l3' },
              { kind: 'I32Load'; offset: 12 },
              { kind: 'LocalSet'; id: '$l10' },
              { kind: 'Const'; value: 9 },
              { kind: 'LocalSet'; id: '$l11' },
              { kind: 'LocalGet'; id: '$l10' },
              { kind: 'LocalSet'; id: '$l12' },
              { kind: 'LocalGet'; id: '$l11' },
              { kind: 'LocalSet'; id: '$l13' },
              { kind: 'LocalGet'; id: '$l12' },
              { kind: 'LocalGet'; id: '$l13' },
              { kind: 'LessThan' },
              { kind: 'LocalSet'; id: '$l14' },
              { kind: 'Const'; value: 1 },
              { kind: 'LocalSet'; id: '$l15' },
              { kind: 'LocalGet'; id: '$l14' },
              { kind: 'LocalGet'; id: '$l15' },
              { kind: 'And' },
              { kind: 'LocalSet'; id: '$l16' },
              { kind: 'LocalGet'; id: '$l16' },
              { kind: 'EqualsZero' },
              { kind: 'BranchIf'; id: '$B0' },
              { kind: 'Const'; value: 0 },
              { kind: 'LocalSet'; id: '$l17' },
              { kind: 'LocalGet'; id: '$l3' },
              { kind: 'LocalGet'; id: '$l17' },
              { kind: 'I32Store'; offset: 8 },
              { kind: 'Block';
                id: '$B2';
                instructions: [
                  { kind: 'Loop';
                    id: '$L3';
                    instructions: [
                      { kind: 'LocalGet'; id: '$l3' },
                      { kind: 'I32Load'; offset: 8 },
                      { kind: 'LocalSet'; id: '$l18' },
                      { kind: 'Const'; value: 9 },
                      { kind: 'LocalSet'; id: '$l19' },
                      { kind: 'LocalGet'; id: '$l18' },
                      { kind: 'LocalSet'; id: '$l20' },
                      { kind: 'LocalGet'; id: '$l19' },
                      { kind: 'LocalSet'; id: '$l21' },
                      { kind: 'LocalGet'; id: '$l20' },
                      { kind: 'LocalGet'; id: '$l21' },
                      { kind: 'LessThan' },
                      { kind: 'LocalSet'; id: '$l22' },
                      { kind: 'Const'; value: 1 },
                      { kind: 'LocalSet'; id: '$l23' },
                      { kind: 'LocalGet'; id: '$l22' },
                      { kind: 'LocalGet'; id: '$l23' },
                      { kind: 'And' },
                      { kind: 'LocalSet'; id: '$l24' },
                      { kind: 'LocalGet'; id: '$l24' },
                      { kind: 'EqualsZero' },
                      { kind: 'BranchIf'; id: '$B2' },
                      { kind: 'LocalGet'; id: '$l3' },
                      { kind: 'I32Load'; offset: 12 },
                      { kind: 'LocalSet'; id: '$l25' },
                      { kind: 'Const'; value: 16 },
                      { kind: 'LocalSet'; id: '$l26' },
                      { kind: 'LocalGet'; id: '$l3' },
                      { kind: 'LocalGet'; id: '$l26' },
                      { kind: 'Add' },
                      { kind: 'LocalSet'; id: '$l27' },
                      { kind: 'LocalGet'; id: '$l27' },
                      { kind: 'LocalSet'; id: '$l28' },
                      { kind: 'Const'; value: 9 },
                      { kind: 'LocalSet'; id: '$l29' },
                      { kind: 'LocalGet'; id: '$l25' },
                      { kind: 'LocalGet'; id: '$l29' },
                      { kind: 'Multiply' },
                      { kind: 'LocalSet'; id: '$l30' },
                      { kind: 'LocalGet'; id: '$l28' },
                      { kind: 'LocalGet'; id: '$l30' },
                      { kind: 'Add' },
                      { kind: 'LocalSet'; id: '$l31' },
                      { kind: 'LocalGet'; id: '$l3' },
                      { kind: 'I32Load'; offset: 8 },
                      { kind: 'LocalSet'; id: '$l32' },
                      { kind: 'LocalGet'; id: '$l31' },
                      { kind: 'LocalGet'; id: '$l32' },
                      { kind: 'Add' },
                      { kind: 'LocalSet'; id: '$l33' },
                      { kind: 'LocalGet'; id: '$l33' },
                      { kind: 'I32Load8u'; offset: 0 },
                      { kind: 'LocalSet'; id: '$l34' },
                      { kind: 'LocalGet'; id: '$l3' },
                      { kind: 'I32Load'; offset: 12 },
                      { kind: 'LocalSet'; id: '$l35' },
                      { kind: 'Const'; value: 112 },
                      { kind: 'LocalSet'; id: '$l36' },
                      { kind: 'LocalGet'; id: '$l3' },
                      { kind: 'LocalGet'; id: '$l36' },
                      { kind: 'Add' },
                      { kind: 'LocalSet'; id: '$l37' },
                      { kind: 'LocalGet'; id: '$l37' },
                      { kind: 'LocalSet'; id: '$l38' },
                      { kind: 'Const'; value: 9 },
                      { kind: 'LocalSet'; id: '$l39' },
                      { kind: 'LocalGet'; id: '$l35' },
                      { kind: 'LocalGet'; id: '$l39' },
                      { kind: 'Multiply' },
                      { kind: 'LocalSet'; id: '$l40' },
                      { kind: 'LocalGet'; id: '$l38' },
                      { kind: 'LocalGet'; id: '$l40' },
                      { kind: 'Add' },
                      { kind: 'LocalSet'; id: '$l41' },
                      { kind: 'LocalGet'; id: '$l3' },
                      { kind: 'I32Load'; offset: 8 },
                      { kind: 'LocalSet'; id: '$l42' },
                      { kind: 'LocalGet'; id: '$l41' },
                      { kind: 'LocalGet'; id: '$l42' },
                      { kind: 'Add' },
                      { kind: 'LocalSet'; id: '$l43' },
                      { kind: 'LocalGet'; id: '$l43' },
                      { kind: 'LocalGet'; id: '$l34' },
                      { kind: 'I32Store8'; offset: 0 },
                      { kind: 'LocalGet'; id: '$l3' },
                      { kind: 'I32Load'; offset: 8 },
                      { kind: 'LocalSet'; id: '$l44' },
                      { kind: 'Const'; value: 1 },
                      { kind: 'LocalSet'; id: '$l45' },
                      { kind: 'LocalGet'; id: '$l44' },
                      { kind: 'LocalGet'; id: '$l45' },
                      { kind: 'Add' },
                      { kind: 'LocalSet'; id: '$l46' },
                      { kind: 'LocalGet'; id: '$l3' },
                      { kind: 'LocalGet'; id: '$l46' },
                      { kind: 'I32Store'; offset: 8 },
                      { kind: 'Branch'; id: '$L3' },
                    ];
                  },
                  { kind: 'Unreachable' },
                ];
              },
              { kind: 'LocalGet'; id: '$l3' },
              { kind: 'I32Load'; offset: 12 },
              { kind: 'LocalSet'; id: '$l47' },
              { kind: 'Const'; value: 1 },
              { kind: 'LocalSet'; id: '$l48' },
              { kind: 'LocalGet'; id: '$l47' },
              { kind: 'LocalGet'; id: '$l48' },
              { kind: 'Add' },
              { kind: 'LocalSet'; id: '$l49' },
              { kind: 'LocalGet'; id: '$l3' },
              { kind: 'LocalGet'; id: '$l49' },
              { kind: 'I32Store'; offset: 12 },
              { kind: 'Branch'; id: '$L1' },
            ];
          },
          { kind: 'Unreachable' },
        ];
      },
      { kind: 'Const'; value: 0 },
      { kind: 'LocalSet'; id: '$l50' },
      { kind: 'LocalGet'; id: '$l3' },
      { kind: 'LocalGet'; id: '$l50' },
      { kind: 'I32Store'; offset: 4 },
      { kind: 'Block';
        id: '$B4';
        instructions: [
          { kind: 'Loop';
            id: '$L5';
            instructions: [
              { kind: 'LocalGet'; id: '$l3' },
              { kind: 'I32Load'; offset: 4 },
              { kind: 'LocalSet'; id: '$l51' },
              { kind: 'LocalGet'; id: '$l3' },
              { kind: 'I32Load'; offset: 204 },
              { kind: 'LocalSet'; id: '$l52' },
              { kind: 'LocalGet'; id: '$l51' },
              { kind: 'LocalSet'; id: '$l53' },
              { kind: 'LocalGet'; id: '$l52' },
              { kind: 'LocalSet'; id: '$l54' },
              { kind: 'LocalGet'; id: '$l53' },
              { kind: 'LocalGet'; id: '$l54' },
              { kind: 'LessThan' },
              { kind: 'LocalSet'; id: '$l55' },
              { kind: 'Const'; value: 1 },
              { kind: 'LocalSet'; id: '$l56' },
              { kind: 'LocalGet'; id: '$l55' },
              { kind: 'LocalGet'; id: '$l56' },
              { kind: 'And' },
              { kind: 'LocalSet'; id: '$l57' },
              { kind: 'LocalGet'; id: '$l57' },
              { kind: 'EqualsZero' },
              { kind: 'BranchIf'; id: '$B4' },
              { kind: 'Const'; value: 112 },
              { kind: 'LocalSet'; id: '$l58' },
              { kind: 'LocalGet'; id: '$l3' },
              { kind: 'LocalGet'; id: '$l58' },
              { kind: 'Add' },
              { kind: 'LocalSet'; id: '$l59' },
              { kind: 'LocalGet'; id: '$l59' },
              { kind: 'LocalSet'; id: '$l60' },
              { kind: 'Const'; value: 9 },
              { kind: 'LocalSet'; id: '$l61' },
              { kind: 'LocalGet'; id: '$l60' },
              { kind: 'LocalGet'; id: '$l61' },
              { kind: 'LocalGet'; id: '$l61' },
              { kind: 'Call'; id: '$updateGrid' },
              { kind: 'LocalGet'; id: '$l3' },
              { kind: 'I32Load'; offset: 4 },
              { kind: 'LocalSet'; id: '$l62' },
              { kind: 'Const'; value: 1 },
              { kind: 'LocalSet'; id: '$l63' },
              { kind: 'LocalGet'; id: '$l62' },
              { kind: 'LocalGet'; id: '$l63' },
              { kind: 'Add' },
              { kind: 'LocalSet'; id: '$l64' },
              { kind: 'LocalGet'; id: '$l3' },
              { kind: 'LocalGet'; id: '$l64' },
              { kind: 'I32Store'; offset: 4 },
              { kind: 'Branch'; id: '$L5' },
            ];
          },
          { kind: 'Unreachable' },
        ];
      },
      { kind: 'Const'; value: 112 },
      { kind: 'LocalSet'; id: '$l65' },
      { kind: 'LocalGet'; id: '$l3' },
      { kind: 'LocalGet'; id: '$l65' },
      { kind: 'Add' },
      { kind: 'LocalSet'; id: '$l66' },
      { kind: 'LocalGet'; id: '$l66' },
      { kind: 'LocalSet'; id: '$l67' },
      { kind: 'Const'; value: 9 },
      { kind: 'LocalSet'; id: '$l68' },
      { kind: 'LocalGet'; id: '$l67' },
      { kind: 'LocalGet'; id: '$l68' },
      { kind: 'LocalGet'; id: '$l68' },
      { kind: 'Call'; id: '$displayGrid' },
      { kind: 'LocalSet'; id: '$l69' },
      { kind: 'Const'; value: 208 },
      { kind: 'LocalSet'; id: '$l70' },
      { kind: 'LocalGet'; id: '$l3' },
      { kind: 'LocalGet'; id: '$l70' },
      { kind: 'Add' },
      { kind: 'LocalSet'; id: '$l71' },
      { kind: 'LocalGet'; id: '$l71' },
      { kind: 'GlobalSet'; id: '$__stack_pointer' },
      { kind: 'LocalGet'; id: '$l69' },
      { kind: 'Return'; count: 1 },
    ];
  }
> = RESULT

type $_initialize<
  RESULT extends Func = {
    kind: 'func';
    params: [];
    result: number;
    locals: [];
    instructions: [
      { kind: 'Block';
        id: '$B0';
        instructions: [
          { kind: 'Const'; value: 1 },
          { kind: 'EqualsZero' },
          { kind: 'BranchIf'; id: '$B0' },
          { kind: 'Call'; id: '$__wasm_call_ctors' },
        ];
      },
    ];
  }
> = RESULT

type $__memcpy<
  RESULT extends Func = {
    kind: 'func';
    params: ['$p0', '$p1', '$p2'];
    result: number;
    locals: ['$l3', '$l4', '$l5'];
    instructions: [
      { kind: 'LocalGet'; id: '$p0' },
      { kind: 'LocalGet'; id: '$p2' },
      { kind: 'Add' },
      { kind: 'LocalSet'; id: '$l3' },
      { kind: 'Block';
        id: '$B0';
        instructions: [
          { kind: 'Block';
            id: '$B1';
            instructions: [
              { kind: 'Block';
                id: '$B2';
                instructions: [
                  { kind: 'Block';
                    id: '$B3';
                    instructions: [
                      { kind: 'LocalGet'; id: '$p1' },
                      { kind: 'LocalGet'; id: '$p0' },
                      { kind: 'Xor' },
                      { kind: 'Const'; value: 3 },
                      { kind: 'And' },
                      { kind: 'BranchIf'; id: '$B3' },
                      { kind: 'LocalGet'; id: '$p0' },
                      { kind: 'Const'; value: 3 },
                      { kind: 'And' },
                      { kind: 'EqualsZero' },
                      { kind: 'BranchIf'; id: '$B2' },
                      { kind: 'LocalGet'; id: '$p2' },
                      { kind: 'Const'; value: 1 },
                      { kind: 'LessThan' },
                      { kind: 'BranchIf'; id: '$B2' },
                      { kind: 'LocalGet'; id: '$p0' },
                      { kind: 'LocalSet'; id: '$p2' },
                      { kind: 'Loop';
                        id: '$L4';
                        instructions: [
                          { kind: 'LocalGet'; id: '$p2' },
                          { kind: 'LocalGet'; id: '$p1' },
                          { kind: 'I32Load8u'; offset: 0 },
                          { kind: 'I32Store8'; offset: 0 },
                          { kind: 'LocalGet'; id: '$p1' },
                          { kind: 'Const'; value: 1 },
                          { kind: 'Add' },
                          { kind: 'LocalSet'; id: '$p1' },
                          { kind: 'LocalGet'; id: '$p2' },
                          { kind: 'Const'; value: 1 },
                          { kind: 'Add' },
                          { kind: 'LocalTee'; id: '$p2' },
                          { kind: 'Const'; value: 3 },
                          { kind: 'And' },
                          { kind: 'EqualsZero' },
                          { kind: 'BranchIf'; id: '$B1' },
                          { kind: 'LocalGet'; id: '$p2' },
                          { kind: 'LocalGet'; id: '$l3' },
                          { kind: 'LessThan' },
                          { kind: 'BranchIf'; id: '$L4' },
                          { kind: 'Branch'; id: '$B1' },
                        ];
                      },
                      { kind: 'Unreachable' },
                    ];
                  },
                  { kind: 'Block';
                    id: '$B5';
                    instructions: [
                      { kind: 'LocalGet'; id: '$l3' },
                      { kind: 'Const'; value: 4 },
                      { kind: 'LessThan' },
                      { kind: 'BranchIf'; id: '$B5' },
                      { kind: 'LocalGet'; id: '$l3' },
                      { kind: 'Const'; value: -4 },
                      { kind: 'Add' },
                      { kind: 'LocalTee'; id: '$l4' },
                      { kind: 'LocalGet'; id: '$p0' },
                      { kind: 'LessThan' },
                      { kind: 'BranchIf'; id: '$B5' },
                      { kind: 'LocalGet'; id: '$p0' },
                      { kind: 'LocalSet'; id: '$p2' },
                      { kind: 'Loop';
                        id: '$L6';
                        instructions: [
                          { kind: 'LocalGet'; id: '$p2' },
                          { kind: 'LocalGet'; id: '$p1' },
                          { kind: 'I32Load8u'; offset: 0 },
                          { kind: 'I32Store8'; offset: 0 },
                          { kind: 'LocalGet'; id: '$p2' },
                          { kind: 'LocalGet'; id: '$p1' },
                          { kind: 'I32Load8u'; offset: 1 },
                          { kind: 'I32Store8'; offset: 1 },
                          { kind: 'LocalGet'; id: '$p2' },
                          { kind: 'LocalGet'; id: '$p1' },
                          { kind: 'I32Load8u'; offset: 2 },
                          { kind: 'I32Store8'; offset: 2 },
                          { kind: 'LocalGet'; id: '$p2' },
                          { kind: 'LocalGet'; id: '$p1' },
                          { kind: 'I32Load8u'; offset: 3 },
                          { kind: 'I32Store8'; offset: 3 },
                          { kind: 'LocalGet'; id: '$p1' },
                          { kind: 'Const'; value: 4 },
                          { kind: 'Add' },
                          { kind: 'LocalSet'; id: '$p1' },
                          { kind: 'LocalGet'; id: '$p2' },
                          { kind: 'Const'; value: 4 },
                          { kind: 'Add' },
                          { kind: 'LocalTee'; id: '$p2' },
                          { kind: 'LocalGet'; id: '$l4' },
                          { kind: 'LessThanOrEqual' },
                          { kind: 'BranchIf'; id: '$L6' },
                          { kind: 'Branch'; id: '$B0' },
                        ];
                      },
                      { kind: 'Unreachable' },
                    ];
                  },
                  { kind: 'LocalGet'; id: '$p0' },
                  { kind: 'LocalSet'; id: '$p2' },
                  { kind: 'Branch'; id: '$B0' },
                ];
              },
              { kind: 'LocalGet'; id: '$p0' },
              { kind: 'LocalSet'; id: '$p2' },
            ];
          },
          { kind: 'Block';
            id: '$B7';
            instructions: [
              { kind: 'LocalGet'; id: '$l3' },
              { kind: 'Const'; value: -4 },
              { kind: 'And' },
              { kind: 'LocalTee'; id: '$l4' },
              { kind: 'Const'; value: 64 },
              { kind: 'LessThan' },
              { kind: 'BranchIf'; id: '$B7' },
              { kind: 'LocalGet'; id: '$p2' },
              { kind: 'LocalGet'; id: '$l4' },
              { kind: 'Const'; value: -64 },
              { kind: 'Add' },
              { kind: 'LocalTee'; id: '$l5' },
              { kind: 'GreaterThan' },
              { kind: 'BranchIf'; id: '$B7' },
              { kind: 'Loop';
                id: '$L8';
                instructions: [
                  { kind: 'LocalGet'; id: '$p2' },
                  { kind: 'LocalGet'; id: '$p1' },
                  { kind: 'I32Load'; offset: 0 },
                  { kind: 'I32Store'; offset: 0 },
                  { kind: 'LocalGet'; id: '$p2' },
                  { kind: 'LocalGet'; id: '$p1' },
                  { kind: 'I32Load'; offset: 4 },
                  { kind: 'I32Store'; offset: 4 },
                  { kind: 'LocalGet'; id: '$p2' },
                  { kind: 'LocalGet'; id: '$p1' },
                  { kind: 'I32Load'; offset: 8 },
                  { kind: 'I32Store'; offset: 8 },
                  { kind: 'LocalGet'; id: '$p2' },
                  { kind: 'LocalGet'; id: '$p1' },
                  { kind: 'I32Load'; offset: 12 },
                  { kind: 'I32Store'; offset: 12 },
                  { kind: 'LocalGet'; id: '$p2' },
                  { kind: 'LocalGet'; id: '$p1' },
                  { kind: 'I32Load'; offset: 16 },
                  { kind: 'I32Store'; offset: 16 },
                  { kind: 'LocalGet'; id: '$p2' },
                  { kind: 'LocalGet'; id: '$p1' },
                  { kind: 'I32Load'; offset: 20 },
                  { kind: 'I32Store'; offset: 20 },
                  { kind: 'LocalGet'; id: '$p2' },
                  { kind: 'LocalGet'; id: '$p1' },
                  { kind: 'I32Load'; offset: 24 },
                  { kind: 'I32Store'; offset: 24 },
                  { kind: 'LocalGet'; id: '$p2' },
                  { kind: 'LocalGet'; id: '$p1' },
                  { kind: 'I32Load'; offset: 28 },
                  { kind: 'I32Store'; offset: 28 },
                  { kind: 'LocalGet'; id: '$p2' },
                  { kind: 'LocalGet'; id: '$p1' },
                  { kind: 'I32Load'; offset: 32 },
                  { kind: 'I32Store'; offset: 32 },
                  { kind: 'LocalGet'; id: '$p2' },
                  { kind: 'LocalGet'; id: '$p1' },
                  { kind: 'I32Load'; offset: 36 },
                  { kind: 'I32Store'; offset: 36 },
                  { kind: 'LocalGet'; id: '$p2' },
                  { kind: 'LocalGet'; id: '$p1' },
                  { kind: 'I32Load'; offset: 40 },
                  { kind: 'I32Store'; offset: 40 },
                  { kind: 'LocalGet'; id: '$p2' },
                  { kind: 'LocalGet'; id: '$p1' },
                  { kind: 'I32Load'; offset: 44 },
                  { kind: 'I32Store'; offset: 44 },
                  { kind: 'LocalGet'; id: '$p2' },
                  { kind: 'LocalGet'; id: '$p1' },
                  { kind: 'I32Load'; offset: 48 },
                  { kind: 'I32Store'; offset: 48 },
                  { kind: 'LocalGet'; id: '$p2' },
                  { kind: 'LocalGet'; id: '$p1' },
                  { kind: 'I32Load'; offset: 52 },
                  { kind: 'I32Store'; offset: 52 },
                  { kind: 'LocalGet'; id: '$p2' },
                  { kind: 'LocalGet'; id: '$p1' },
                  { kind: 'I32Load'; offset: 56 },
                  { kind: 'I32Store'; offset: 56 },
                  { kind: 'LocalGet'; id: '$p2' },
                  { kind: 'LocalGet'; id: '$p1' },
                  { kind: 'I32Load'; offset: 60 },
                  { kind: 'I32Store'; offset: 60 },
                  { kind: 'LocalGet'; id: '$p1' },
                  { kind: 'Const'; value: 64 },
                  { kind: 'Add' },
                  { kind: 'LocalSet'; id: '$p1' },
                  { kind: 'LocalGet'; id: '$p2' },
                  { kind: 'Const'; value: 64 },
                  { kind: 'Add' },
                  { kind: 'LocalTee'; id: '$p2' },
                  { kind: 'LocalGet'; id: '$l5' },
                  { kind: 'LessThanOrEqual' },
                  { kind: 'BranchIf'; id: '$L8' },
                ];
              },
            ];
          },
          { kind: 'LocalGet'; id: '$p2' },
          { kind: 'LocalGet'; id: '$l4' },
          { kind: 'GreaterThanOrEqual' },
          { kind: 'BranchIf'; id: '$B0' },
          { kind: 'Loop';
            id: '$L9';
            instructions: [
              { kind: 'LocalGet'; id: '$p2' },
              { kind: 'LocalGet'; id: '$p1' },
              { kind: 'I32Load'; offset: 0 },
              { kind: 'I32Store'; offset: 0 },
              { kind: 'LocalGet'; id: '$p1' },
              { kind: 'Const'; value: 4 },
              { kind: 'Add' },
              { kind: 'LocalSet'; id: '$p1' },
              { kind: 'LocalGet'; id: '$p2' },
              { kind: 'Const'; value: 4 },
              { kind: 'Add' },
              { kind: 'LocalTee'; id: '$p2' },
              { kind: 'LocalGet'; id: '$l4' },
              { kind: 'LessThan' },
              { kind: 'BranchIf'; id: '$L9' },
            ];
          },
        ];
      },
      { kind: 'Block';
        id: '$B10';
        instructions: [
          { kind: 'LocalGet'; id: '$p2' },
          { kind: 'LocalGet'; id: '$l3' },
          { kind: 'GreaterThanOrEqual' },
          { kind: 'BranchIf'; id: '$B10' },
          { kind: 'Loop';
            id: '$L11';
            instructions: [
              { kind: 'LocalGet'; id: '$p2' },
              { kind: 'LocalGet'; id: '$p1' },
              { kind: 'I32Load8u'; offset: 0 },
              { kind: 'I32Store8'; offset: 0 },
              { kind: 'LocalGet'; id: '$p1' },
              { kind: 'Const'; value: 1 },
              { kind: 'Add' },
              { kind: 'LocalSet'; id: '$p1' },
              { kind: 'LocalGet'; id: '$p2' },
              { kind: 'Const'; value: 1 },
              { kind: 'Add' },
              { kind: 'LocalTee'; id: '$p2' },
              { kind: 'LocalGet'; id: '$l3' },
              { kind: 'NotEqual' },
              { kind: 'BranchIf'; id: '$L11' },
            ];
          },
        ];
      },
      { kind: 'LocalGet'; id: '$p0' },
    ];
  }
> = RESULT

type $stackSave<
  RESULT extends Func = {
    kind: 'func';
    params: [];
    result: number;
    locals: [];
    instructions: [
      { kind: 'GlobalGet'; id: '$__stack_pointer' },
    ];
  }
> = RESULT

type $stackRestore<
  RESULT extends Func = {
    kind: 'func';
    params: ['$p0'];
    result: number;
    locals: [];
    instructions: [
      { kind: 'LocalGet'; id: '$p0' },
      { kind: 'GlobalSet'; id: '$__stack_pointer' },
    ];
  }
> = RESULT

type $stackAlloc<
  RESULT extends Func = {
    kind: 'func';
    params: ['$p0'];
    result: number;
    locals: ['$l1', '$l2'];
    instructions: [
      { kind: 'GlobalGet'; id: '$__stack_pointer' },
      { kind: 'LocalGet'; id: '$p0' },
      { kind: 'Subtract' },
      { kind: 'Const'; value: -16 },
      { kind: 'And' },
      { kind: 'LocalTee'; id: '$l1' },
      { kind: 'GlobalSet'; id: '$__stack_pointer' },
      { kind: 'LocalGet'; id: '$l1' },
    ];
  }
> = RESULT

type $emscripten_stack_init<
  RESULT extends Func = {
    kind: 'func';
    params: [];
    result: number;
    locals: [];
    instructions: [
      { kind: 'Const'; value: 5244096 },
      { kind: 'GlobalSet'; id: '$__stack_base' },
      { kind: 'Const'; value: 1208 },
      { kind: 'Const'; value: 15 },
      { kind: 'Add' },
      { kind: 'Const'; value: -16 },
      { kind: 'And' },
      { kind: 'GlobalSet'; id: '$__stack_end' },
    ];
  }
> = RESULT

type $emscripten_stack_get_free<
  RESULT extends Func = {
    kind: 'func';
    params: [];
    result: number;
    locals: [];
    instructions: [
      { kind: 'GlobalGet'; id: '$__stack_pointer' },
      { kind: 'GlobalGet'; id: '$__stack_end' },
      { kind: 'Subtract' },
    ];
  }
> = RESULT

type $emscripten_stack_get_base<
  RESULT extends Func = {
    kind: 'func';
    params: [];
    result: number;
    locals: [];
    instructions: [
      { kind: 'GlobalGet'; id: '$__stack_base' },
    ];
  }
> = RESULT

type $emscripten_stack_get_end<
  RESULT extends Func = {
    kind: 'func';
    params: [];
    result: number;
    locals: [];
    instructions: [
      { kind: 'GlobalGet'; id: '$__stack_end' },
    ];
  }
> = RESULT

type $__errno_location<
  RESULT extends Func = {
    kind: 'func';
    params: [];
    result: number;
    locals: [];
    instructions: [
      { kind: 'Const'; value: 1204 },
    ];
  }
> = RESULT

export type entry<
  arguments extends number[] = [],
  debugMode extends boolean = false
> = runProgram<
  {
    arguments: arguments;
    funcs: {
      $__wasm_call_ctors: $__wasm_call_ctors;
      $countAliveNeighbors: $countAliveNeighbors;
      $updateGrid: $updateGrid;
      $displayGrid: $displayGrid;
      $entry: $entry;
      $_initialize: $_initialize;
      $__memcpy: $__memcpy;
      $stackSave: $stackSave;
      $stackRestore: $stackRestore;
      $stackAlloc: $stackAlloc;
      $emscripten_stack_init: $emscripten_stack_init;
      $emscripten_stack_get_free: $emscripten_stack_get_free;
      $emscripten_stack_get_base: $emscripten_stack_get_base;
      $emscripten_stack_get_end: $emscripten_stack_get_end;
      $__errno_location: $__errno_location;
    };
    globals: {
      $__stack_pointer: 5244096;
      $__stack_end: 0;
      $__stack_base: 0;
    };
    memory: 
      & StoreString<1024, $_rodata>
    ;
    memorySize: 256;
    indirect: ['$__wasm_call_ctors'];
  },
  debugMode
>
type $_rodata = `                                                                          `;
