
// import type { Add } from "ts-type-math"; // the hotscript implementation

// import type {Add} from "ts-arithmetic"

import type { Sum as Add } from "./ch3cknull-dimitri"; // dummy implementation, as a baseline

type v = [
  "1234",
  "1234567",
  "1234567890",
  "1234567890123",
]

export type e =
Add<
  "1",
  Add<
    Add<
      Add<
        Add<
          v[0],
          Add<
            v[1],
            Add<
              v[2],
              v[3]
            >
          >
        >,
        Add<
          v[0],
          Add<
            v[1],
            Add<
              v[2],
              v[3]
            >
          >
        >
      >,
      Add<
        Add<
          v[0],
          Add<
            v[1],
            Add<
              v[2],
              v[3]
            >
          >
        >,
        Add<
          v[0],
          Add<
            v[1],
            Add<
              v[2],
              v[3]
            >
          >
        >
      >
    >,
    Add<
      Add<
        Add<
          v[0],
          Add<
            v[1],
            Add<
              v[2],
              v[3]
            >
          >
        >,
        Add<
          v[0],
          Add<
            v[1],
            Add<
              v[2],
              v[3]
            >
          >
        >
      >,
      Add<
        Add<
          v[0],
          Add<
            v[1],
            Add<
              v[2],
              v[3]
            >
          >
        >,
        Add<
          v[0],
          Add<
            v[1],
            Add<
              v[2],
              Add<
                v[0],
                Add<
                  v[1],
                  Add<
                    v[2],
                    Add<
                      v[0],
                      Add<
                        v[1],
                        Add<
                          v[2],
                          Add<
                            v[0],
                            Add<
                              v[1],
                              Add<
                                v[2],
                                Add<
                                  v[0],
                                  Add<
                                    v[1],
                                    Add<
                                      v[2],
                                      Add<
                                        v[0],
                                        Add<
                                          v[1],
                                          Add<
                                            v[2],
                                            Add<
                                              v[0],
                                              Add<
                                                v[1],
                                                Add<
                                                  v[2],
                                                  Add<
                                                    v[0],
                                                    Add<
                                                      v[1],
                                                      Add<
                                                        v[2],
                                                        Add<
                                                          v[0],
                                                          Add<
                                                            v[1],
                                                            Add<
                                                              v[2],
                                                              Add<
                                                                v[0],
                                                                Add<
                                                                  v[1],
                                                                  Add<
                                                                    v[2],
                                                                    v[3]
                                                                  >
                                                                >
                                                              >
                                                            >
                                                          >
                                                        >
                                                      >
                                                    >
                                                  >
                                                >
                                              >
                                            >
                                          >
                                        >
                                      >
                                    >
                                  >
                                >
                              >
                            >
                          >
                        >
                      >
                    >
                  >
                >
              >
            >
          >
        >
      >
    >
  >
>
