clang \
  pong.c \
  --target=wasm32 \
  -nostdlib \
  -nostdinc \
  -ffreestanding \
  -m32 \
  -O0 \
  -Wall \
  -ggdb3 \
  -g \
  -Wl,--export=entry \
  -Wl,--import-memory \
  -Wl,--no-entry \
  -o pong.wasm

wasm2wat \
  pong.wasm \
  --enable-code-metadata \
  --inline-exports \
  --inline-imports \
  --disable-reference-types \
  --generate-names \
  --fold-expr \
  --output pong.wat