import { Convert, Wasm, WasmType, WasmValue, Store, evaluate } from "ts-type-math";
import { Func } from "wasm-to-typescript-types";
import { entry as bareEntry, funcs as bareFuncs } from "./pong.ts";
import { MemoryByAddress, ProgramState } from "../../wasm-to-typescript-types/types.ts";

type $env_render = Satisfies<Func, {
  kind: 'func';
  params: [];
  paramsTypes: [];
  resultTypes: [WasmType];
  locals: [];
  instructions: [
    { kind: 'Halt' },
  ];
}>

type Repeat<
  Value extends number,
  Count extends number,
  _Acc extends Value[] = [],
> =
  Count extends _Acc['length']
  ? _Acc
  : Repeat<Value, Count, [Value, ..._Acc]>

type none<Count extends number> = Repeat<0, Count>;
type up<Count extends number> = Repeat<1, Count>;
type down<Count extends number> = Repeat<2, Count>;

export type ButtonPresses = [
  ...down<5>,
  ...none<5>,
  ...up<10>,
  ...down<20>,
  ...none<5>,
  ...down<29>,
  ...none<15>,
  ...up<50>,
  ...none<100>,
  ...down<50>,
  ...up<25>,
  ...none<35>,
  ...down<20>,
  ...none<11>,
  ...up<20>,
  ...none<20>,
]

type StartAddress = 0;

type InputMemory<
  Inputs extends readonly number[],

  _Address extends WasmValue = Convert.TSNumber.ToWasmValue<StartAddress, 'i32'>,
  _Acc extends MemoryByAddress = {},
> =
  Inputs extends [
    infer head extends number,
    ...infer tail extends number[]
  ]
  ? InputMemory<
      tail,
      Wasm.I32Add<_Address, Wasm.I32True>,
      _Acc & {
        [key in _Address]:
          Store.GetLSB<
            Convert.TSNumber.ToWasmValue<head, 'i32'>
          >[0]
      }
    >
  : evaluate<_Acc>;

export type funcs = bareFuncs & { $env_render: $env_render };

export type entry<
  args extends readonly number[],
  debugMode extends boolean = false,
  stopAt extends number = number,
> = Satisfies<ProgramState,
  bareEntry<[0, args['length']], debugMode, stopAt> extends infer Bare extends ProgramState
  ? {
    count: Bare['count'],
    stack: Bare['stack'],
    activeFuncId: Bare['activeFuncId'],
    activeStackDepth: Bare['activeStackDepth'],
    activeLocals: Bare['activeLocals'],
    instructions: Bare['instructions'],
    activeBranches: Bare['activeBranches'],
    L1Cache: InputMemory<args>, // patch
    memory: Bare['memory'],
    executionContexts: Bare['executionContexts'],
    funcs: funcs, // patch
    garbageCollection: Bare['garbageCollection'],
    globals: Bare['globals'],
    memorySize: Bare['memorySize'],
    indirect: Bare['indirect'],
    results: Bare['results'],
    callHistory: Bare['callHistory'],
  }
  : never
>;

/** an example frame */
export type PongFrame = {
  "0000": "                                                                                                                                                ######          ||            ####                                                                                                                                              ", 
  "0001": "                                                                                                                                              ##    ####        ||        ########                                                                                                                                              ", 
  "0002": "                                                                                                                                            ####      ####      ||            ####                                                                                                                                              ", 
  "0003": "                                                                                                                                            ####      ####      ||            ####                                                                                                                                              ", 
  "0004": "                                                                                                                                            ####      ####      ||            ####                                                                                                                                              ", 
  "0005": "                                                                                                                                              ####    ##        ||            ####                                                                                                                                              ", 
  "0006": "                                                                                                                                                ######          ||      ##############                                                                                                                                          ", 
  "0007": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0008": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0009": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0010": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0011": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0012": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0013": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0014": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0015": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0016": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0017": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0018": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0019": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0020": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0021": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0022": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0023": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0024": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0025": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0026": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0027": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0028": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0029": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0030": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0031": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0032": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0033": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0034": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0035": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0036": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0037": "                                                                            0000                                                                                ||                                                                                                                                                              ", 
  "0038": "==========                                                                00000000                                                                              ||                                                                                                                                                              ", 
  "0039": "==......==                                                                00000000                                                                              ||                                                                                                                                                              ", 
  "0040": "==......==                                                                  0000                                                                                ||                                                                                                                                                              ", 
  "0041": "==......==                                                                                                                                                      ||                                                                                                                                                              ", 
  "0042": "==......==                                                                                                                                                      ||                                                                                                                                                              ", 
  "0043": "==......==                                                                                                                                                      ||                                                                                                                                                              ", 
  "0044": "==......==                                                                                                                                                      ||                                                                                                                                                              ", 
  "0045": "==......==                                                                                                                                                      ||                                                                                                                                                              ", 
  "0046": "==......==                                                                                                                                                      ||                                                                                                                                                              ", 
  "0047": "==......==                                                                                                                                                      ||                                                                                                                                                              ", 
  "0048": "==......==                                                                                                                                                      ||                                                                                                                                                              ", 
  "0049": "==......==                                                                                                                                                      ||                                                                                                                                                              ", 
  "0050": "==......==                                                                                                                                                      ||                                                                                                                                                              ", 
  "0051": "==......==                                                                                                                                                      ||                                                                                                                                                              ", 
  "0052": "==========                                                                                                                                                      ||                                                                                                                                                              ", 
  "0053": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0054": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0055": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0056": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0057": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0058": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0059": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0060": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0061": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0062": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0063": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0064": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0065": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0066": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0067": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0068": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0069": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0070": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0071": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0072": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0073": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0074": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0075": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0076": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0077": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0078": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0079": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0080": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0081": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0082": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0083": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0084": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0085": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0086": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0087": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0088": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0089": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0090": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0091": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0092": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0093": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0094": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0095": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0096": "                                                                                                                                                                ||                                                                                                                                                    ==========", 
  "0097": "                                                                                                                                                                ||                                                                                                                                                    ==......==", 
  "0098": "                                                                                                                                                                ||                                                                                                                                                    ==......==", 
  "0099": "                                                                                                                                                                ||                                                                                                                                                    ==......==", 
  "0100": "                                                                                                                                                                ||                                                                                                                                                    ==......==", 
  "0101": "                                                                                                                                                                ||                                                                                                                                                    ==......==", 
  "0102": "                                                                                                                                                                ||                                                                                                                                                    ==......==", 
  "0103": "                                                                                                                                                                ||                                                                                                                                                    ==......==", 
  "0104": "                                                                                                                                                                ||                                                                                                                                                    ==......==", 
  "0105": "                                                                                                                                                                ||                                                                                                                                                    ==......==", 
  "0106": "                                                                                                                                                                ||                                                                                                                                                    ==......==", 
  "0107": "                                                                                                                                                                ||                                                                                                                                                    ==......==", 
  "0108": "                                                                                                                                                                ||                                                                                                                                                    ==......==", 
  "0109": "                                                                                                                                                                ||                                                                                                                                                    ==......==", 
  "0110": "                                                                                                                                                                ||                                                                                                                                                    ==========", 
  "0111": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0112": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0113": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0114": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0115": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0116": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0117": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0118": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0119": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0120": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0121": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0122": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0123": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0124": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0125": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0126": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0127": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0128": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0129": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0130": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0131": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0132": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0133": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0134": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0135": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0136": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0137": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0138": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0139": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0140": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0141": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0142": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0143": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0144": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0145": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0146": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0147": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0148": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0149": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0150": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0151": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0152": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0153": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0154": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0155": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0156": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0157": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0158": "                                                                                                                                                                ||                                                                                                                                                              ", 
  "0159": "                                                                                                                                                                ||                                                                                                                                                              ", 
};